version: '3.7'
services:
  db:
    image: postgres:latest
    env_file: .env
    volumes: 
      - ./data/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    image: api
    build: ./api
    working_dir: /var/www/
    volumes:
      - ./api:/var/www/
      - ./api/public:/var/www/html/
    ports: 
      - 8200:80
    depends_on:
      - db
  front-continental:
    image: node:20-alpine
    working_dir: /app
    command: "npm run start"
    volumes:
      - ./front-continental:/app
    ports:
      - 3000:3000
    depends_on:
      -  db
  phppgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@emial.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    depends_on:
      - db

  
